apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  namespace: flask
  labels:
    app: employees
spec:
  containers:
  - name: flask
    image: 661484852155.dkr.ecr.us-east-1.amazonaws.com/clo835assignment2:flask-v1.0
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-service.sql.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "db_pass123"
    - name: DATABASE
      value: "employees"
  imagePullSecrets:
  - name: ecr-secret

