apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
spec:
  selector:
    app: employees  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  
  type: NodePort  
